config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :topics do
    resources :posts do
      member do
        post :updatestatus
        delete :delete_attached_image
      end
      resources :comments do
        member do
          post :user_comment_rating
        end
      end
      resources :ratings
    end
  end

  resources :posts

  root 'topics#index'
end

app/models/topic.rb
class Topic < ApplicationRecord

  #############  Association ###################
  has_many :posts, dependent: :destroy

  #############  Validation  ###################
  validates :name,length: {minimum: 2}
  validates :price,numericality: { other_than: 0 }

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, unless: ->{ request.format.html? }
  # GET /topics or /topics.json
  def index
    @topics = Topic.all
    respond_to do |format|
      format.json { render json: @topics }
      format.html
    end

  end

  # GET /topics/1 or /topics/1.json
  def show
    @topic = Topic.find(params[:id])
    respond_to do |format|
      format.json { render json: @topic }
      format.html
    end
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:name, :price)
    end
end

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= form_for @topic do |topic| %>
  <div>
    <form class="form">

      <div class="form-group">
        <topic.label for="name">Name</topic.label>
        <%= topic.text_field :name, class: "form-control", placeholder: 'Enter Topic Name' %>
      </div>

      <% if @topic.errors.include?(:name) %>
        <div class="invalid-feedback d-block">
          <% @topic.errors.full_messages_for(:name).each do |message| %>
            <%= message %><br/>
          <% end %>
        </div>
      <% end %>

      <div class="form-group">
        <topic.label for="price">Price</topic.label>
        <%= topic.text_field :price, class: "form-control", placeholder: 'Enter Topic Price' %>
      </div>

      <% if @topic.errors.include?(:price) %>
        <div class="invalid-feedback d-block">
          <% @topic.errors.full_messages_for(:price).each do |message| %>
            <%= message %><br/>
          <% end %>
        </div>
      <% end %>

      <button type="submit" class="btn btn-success">Update Topic</button>

    </form>
  </div>
<% end %>
<br/>

<%= link_to 'Show', @topic, class: 'btn btn-primary' %> |
<%= link_to 'Back', topics_path, class: 'btn btn-secondary' %>

app/views/topics/index.html.erb
<h1>Topics</h1>

<table class="table table-bordered">
  <thead>
    <tr align="center">
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr align="center">
        <td><%= link_to topic.name, topic_posts_path(topic) %></td>
        <td><%= topic.price %></td>
        <td><%= link_to 'Show', topic, class: 'btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic),class: 'btn btn-primary' %></td>
        <td><%= link_to 'Delete', topic, :data => {confirm: 'Are you sure?'}, :method => :delete, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path, class: 'btn btn-success' %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= form_for @topic do |topic| %>
  <div>
    <form class="form">

      <div class="form-group">
        <topic.label for="name">Name</topic.label>
        <%= topic.text_field :name, class: "form-control", placeholder: 'Enter Topic Name' %>
      </div>

      <% if @topic.errors.include?(:name) %>
        <div class="invalid-feedback d-block">
          <% @topic.errors.full_messages_for(:name).each do |message| %>
            <%= message %><br/>
          <% end %>
        </div>
      <% end %>

      <div class="form-group">
        <topic.label for="price">Price</topic.label>
        <%= topic.text_field :price, class: "form-control", placeholder: 'Enter Topic Price' %>
      </div>

      <% if @topic.errors.include?(:price) %>
        <div class="invalid-feedback d-block">
          <% @topic.errors.full_messages_for(:price).each do |message| %>
            <%= message %><br/>
          <% end %>
        </div>
      <% end %>

      <button type="submit" class="btn btn-success">Add Topic</button>

    </form>
  </div>
<% end %>
<br/><%= link_to 'Back', topics_path, class: 'btn btn-secondary' %>

app/views/topics/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @topic.price %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>