config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :topics do
    resources :posts do
      member do
        post :updatestatus
        delete :delete_attached_image
      end
      resources :comments do
        member do
          post :user_comment_rating
        end
      end
      resources :ratings
    end
  end

  resources :posts

  root 'topics#index'
end

app/models/post.rb
class Post < ApplicationRecord

  ############### Scope ###############
  scope :posts_datepicker, -> (from_date,to_date) { where("DATE(created_at)>=?", from_date).where("DATE(created_at)<=?", to_date)}

  ############### Association #####################
  belongs_to :topic, inverse_of: :posts
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags
  has_many :ratings, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :users, join_table: 'posts_users_read_status', class_name: "User"

  ############### Validation   ###################
  validates :name, :length => {:minimum => 1, :maximum => 20}
  validates :content, :length => {:minimum =>1, :maximum => 20}

  ############## Accept nested attribute to alter model to model ####################
  accepts_nested_attributes_for :tags, reject_if: Proc.new { |attributes| Tag.where(tag: attributes['tag']).first.present? || attributes['tag'].blank? }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  include Pagy::Backend
  load_and_authorize_resource
  before_action :get_topic, except: [:index]
  before_action :get_post, only: [ :show, :edit, :update, :destroy, :delete_attached_image ]
  def index
    if params[:topic_id].nil?
      if params[:from_date].present?
        @pagy, @post = pagy(Post.all.posts_datepicker(params[:from_date],params[:to_date]), page: params[:page], items: 10)
      else
        @pagy, @post = pagy(Post.all.posts_datepicker(Date.today-1,Date.today), page: params[:page], items: 10)
      end
    else
      @topic = Topic.find(params[:topic_id])
      @post = @topic.posts
      @new_post = @topic.posts.build
    end
  end

  def show
    @rating = @post.ratings.new
    @comment = @post.comments.new
  end

  def updatestatus
    @post.users << current_user
  end

  def delete_attached_image
    @image = @post.image
    @image.purge
    redirect_to edit_topic_post_path(@topic,@post)
  end

  def new
    respond_to do |format|
      format.js
    end
  end

  def create
    @post = @topic.posts.build(post_params.merge(user_id: current_user.id, comments_count: 0, rating_average: 0.0))
    respond_to do |format|
      if @post.save
        format.js
      else
        format.js
      end
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to topic_posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to topic_posts_path
  end

  private
    def get_topic
      @topic = Topic.find(params[:topic_id])
    end

    def get_post
      @post = @topic.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :content, :image, :topic_id,tag_ids: [],tags_attributes: [:id,:tag] )
    end
end

app/views/posts/_alert.js.erb
alert("Post created successfully");

app/views/posts/_error_messages.html.erb
<div class="error-explanation">
  <h2>
    <%= pluralize(@post.errors.count,"errors") %>prohibitetd this <%= @post.class.to_s.underscore.humanize.downcase %> from being saved
  </h2>
  <% @post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: [@topic,post],local: true) do |form| %>
  <div>
    <form class="form">

      <div class="invalid-feedback d-block">
        <% if post.errors.any? %>
          <% post.errors.full_messages.each do |message| %>
            <%= message %><br/>
          <% end %>
        <% end %>
      </div>


      <div class="form-group">
        <form.label for="name">Name</form.label>
        <%= form.text_field :name, class: "form-control", placeholder: "Enter Post Name" %>
      </div>

      <div class="form-group">
        <form.label for="content">Content</form.label>
        <%= form.text_area :content, class: "form-control", placeholder: "Enter Post Content" %>
      </div>

      <div class="form-group">
        <form.label for="image">Image</form.label><br/>
        <% if @post.image.attached? %>
          <p>You have already attached image:</p>
          <%= link_to 'Show', @post.image %> |
          <%= link_to 'Delete', delete_attached_image_topic_post_path(@topic,post), data: { confirm: "Are you sure to delete the image?" }, method: :delete %>
        <% end %><br>
        <%= form.file_field :image %>
      </div>

      <div class="form-group">
        <%= form.fields_for :tags, @post.tags.new do |i| %>
          <i.label for="tag">Tag</i.label>
          <%= i.text_field :tag,class: "form-control", placeholder: "Enter tag" %>
        <% end %>
      </div>
      <%= form.select :tag_ids, Tag.all.collect{|t| [t.tag,t.id]},{:include_blank => 'Anything'},:multiple => true %><br/>

      <button type="submit" class="btn btn-success">Update Post</button>

    </form>
  </div>
  <br/><%= link_to 'Back', topic_posts_path, class: 'btn btn-secondary' %>
<% end %>

app/views/posts/_new.html.erb
<div id="loader">
</div>
<h1><b>New Post</b></h1>
<%= form_with(model: [@topic,post], local: false) do |form| %>
  <div>
    <form class="form">
      <div id="errordivision"></div>
      <div class="form-group">
        <form.label for="name">Name</form.label>
        <%= form.text_field :name, class: "form-control", placeholder: "Enter Post Name" %>
      </div>

      <div class="form-group">
        <form.label for="content">Content</form.label>
        <%= form.text_area :content, class: "form-control", placeholder: "Enter Post Content" %>
      </div>

      <div class="form-group">
        <form.label for="image">Image</form.label><br/>
        <%= form.file_field :image %>
      </div>

      <div class="form-group">
        <%= form.fields_for :tags, post.tags.new do |i| %>
          <i.label for="tag">Tag</i.label>
          <%= i.text_field :tag,class: "form-control", placeholder: "Enter tag" %>
        <% end %>
      </div>
      <%= form.select :tag_ids, Tag.all.collect{|t| [t.tag,t.id]},{:include_blank => 'Nothing'},:multiple => true %><br/>

      <button type="submit" class="btn btn-success">Add Post</button>

    </form>
  </div>
  <br/><%= link_to 'Back', topic_posts_path, class: 'btn btn-secondary' %>
<% end %>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
  document.getElementById("errordivision").innerHTML = "";
  document.querySelector('#errordivision').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render "error_messages", object: @post) %>');
<% else %>
  var spin = '<div class="text-center"><div class="spinner-border" role="status"><span class="sr-only"></span></div></div>'
  $("#loader").html(spin);
  <%= render 'alert' %>
  setTimeout(function(){
  $("#row").append("<tr align=center><td><%= j link_to @post.name+' ('+@post.topic.name+')',[@post.topic,@post] %></td><td><%= j @post.content %></td><td><% if @post.users.map(&:id).include? current_user.id %><%= j "Post Read" %><% else %><%= j "Post Unread" %><% end %></td><td><%= j @post.topic.name %></td><td><%= j @post.comments_count %></td><td><%= j @post.rating_average %></td><td><% if can? :update, @post %><%= j link_to 'Update',edit_topic_post_path(@post.topic,@post),class: 'btn btn-primary' %><% else %><%= j link_to 'Update', "", class: 'btn btn-primary' %><% end %></td><td><% if can? :destroy, @post %><%= j link_to "Delete", [@post.topic, @post], :data =>{:confirm=>"Are you sure?"}, :method=> :delete, class: 'btn btn-danger' %><% else %><%= j link_to "Delete", "", class: 'btn btn-danger' %><% end %></td></tr>");
  $("#new-post").hide();
  },2000);
<% end %>

app/views/posts/edit.html.erb
<h1><b>Update Post</b></h1>
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<% if params[:topic_id].nil? %>
  <br/>
  <div class="container">
    <div class="row justify-content-center">
      <form class="form-inline" action="posts" >
        <div class="form-group">
          <small><b>From date</b></small><p>&nbsp;</p>
          <input id="from_date" type="text" name="from_date" autocomplete="off" style="text-align:center;">
          <p>&emsp;</p>
        </div>
        <div class="form-group">
          <small><b>To date</b></small><p>&nbsp;</p>
          <input id="to_date" type="text" name="to_date" autocomplete="off" style="text-align:center;">
          <p>&emsp;</p>
        </div>
        <input type="submit" value="Show Details" class="btn btn-success">
      </form>
    </div>
  </div>
<% end %>

<script>
  $('#from_date').datepicker({
      format: 'yyyy-mm-dd'
  });
  $('#to_date').datepicker({
      format: 'yyyy-mm-dd'
  });
  var query_params_date = new URLSearchParams(window.location.search);
  if(query_params_date.get('from_date')==null)
  {
      var date = new Date();
      document.getElementById("from_date").value = date.getFullYear()+'-'+(("0"+(date.getMonth()+1)).slice(-2))+'-'+(("0"+(date.getDate()-1)).slice(-2));
      document.getElementById("to_date").value = date.getFullYear()+ '-' + ("0"+(date.getMonth()+1)).slice(-2) + '-' + ("0"+date.getDate()).slice(-2);
  }
  else
  {
      document.getElementById("from_date").value = query_params_date.get('from_date')
      document.getElementById("to_date").value = query_params_date.get('to_date')
  }
</script>

<h1>Posts</h1>
<% if @post.count>0 %>
  <table class="table table-bordered" id="row">
    <thead>
  <tr align="center">
    <th><%= 'Name of the post' %></th>
    <th><%= 'Content' %></th>
    <th><%= 'Status' %></th>
    <th><%= 'Topic name' %></th>
    <th><%= 'Comments' %></th>
    <th><%= 'Ratings Avg' %></th>
    <th><%= 'Update post' %> </th>
    <th><%= 'Delete post' %></th>
  </tr>
  </thead><tbody>
<% @post.includes(:users,:posts_users).each do |post| %>
    <tr align="center">
      <td><%= link_to post.name+' ('+post.topic.name+')',[post.topic,post] %></td>
      <td><%= post.content %></td>
      <td><% if post.users.map(&:id).include? current_user.id %><%= "Post Read" %><% else %><%= "Post Unread" %><% end %></td>
      <td><%= post.topic.name %></td>
      <td><%= post.comments_count %></td>
      <td><%= post.rating_average %></td>
      <td>
        <% if can? :update, post %>
          <%= link_to 'Update',edit_topic_post_path(post.topic,post),class: 'btn btn-primary' %>
        <% else %>
          <button type="button" class="btn btn-primary" disabled>Update</button>
        <% end %>
      </td>
      <td>
        <% if can? :destroy, post %>
          <%= link_to "Delete", [post.topic, post], :data =>{:confirm=>"Are you sure?"}, :method=> :delete, class: 'btn btn-danger' %>
        <% else %>
          <button type="button" class="btn btn-danger" disabled>Delete</button>
        <% end %>
      </td>
    </tr>
    <% end %>
</tbody>
  </table>
<% end %>
<% if params[:topic_id].nil? %>
  <%= render partial: "shared/paginator", locals: { pagy: @pagy }%>
<% else %>
  <%= link_to 'Add post',new_topic_post_path, remote: true, class: 'btn btn-success' %>
  <%= link_to 'Back', topics_path, class: 'btn btn-secondary' %>
  <div id="new-post"></div>
<% end %>

app/views/posts/new.js.erb
$('#new-post').html("<%= j render 'new', post: @post %>");

app/views/posts/show.html.erb
<h1>Post</h1>
<p>
  <b>Name: </b><%= @post.name %><br/>
  <b>Content: </b><%= @post.content %><br>
  <b>Author Name:</b>
  <% if @post.user.present? %>
    <%= @post.user.email %>
  <% end %>
</p>
<% if @post.image.attached? %>
  <%= image_tag @post.image, style: "width: 300px; display: block" %>
<% end %>
<br/><br/>
<h1>Tags</h1>
  <% @post.tags.each do |tag| %>
    <ul>
      <li><%= tag.tag %></li>
    </ul>
  <% end %>
<br/>
<%= render template: 'ratings/index' %>

<%= render template: 'ratings/new' %>
<br/>



<% if @post.comments.count > 0 %>
<h1>Comments</h1>
<table class="table table-bordered">
  <thead>
    <tr align="center">
      <th>Comment</th>
      <th>Author</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @post.comments.includes(:user).each do |comment| %>
    <% if comment.id.present? %>
    <tr align="center">
      <td><%= comment.comment %></td>
      <td><% if comment.user.present? %><%= comment.user.email %><% end %></td>
      <td>
        <% if can? :update, comment %>
          <%= link_to 'Update',edit_topic_post_comment_path(@topic,@post,comment),class: 'btn btn-primary' %>
        <% else %>
          <button type="button" class="btn btn-primary" disabled>Update</button>
        <% end %>
      </td>
      <td>
        <% if can? :destroy, comment %>
          <%= link_to 'Delete',[@topic,@post,comment], method: :delete, :data => { confirm: "Are you sure" }, class: 'btn btn-danger' %>
        <% else %>
          <button type="button" class="btn btn-danger" disabled>Delete</button>
        <% end %>
      </td>
      <td>
        <%= form_for UserCommentRating.new, url: user_comment_rating_topic_post_comment_path(@topic,@post,comment) do |rating| %>
            <%= rating.radio_button :rating, '5 stars' %> 5
            <%= rating.radio_button :rating, '4 stars' %> 4
            <%= rating.radio_button :rating, '3 stars' %> 3
            <%= rating.radio_button :rating, '2 stars' %> 2
            <%= rating.radio_button :rating, '1 star' %> 1
            <%= rating.submit "Add rating", class: 'btn btn-success' %>
        <% end %>
      </td>
      <td><%= link_to "Ratings", topic_post_comment_path(@topic,@post,comment), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<% end %>
<%= form_with(model: [@topic,@post,@comment]) do |comment| %>
  <% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <div class="form-group">
    <label for="comment">Comment:</label>
    <%= comment.text_field :comment, class: 'form-control' %>
  </div>

  <%= comment.submit 'Add comment', class: 'btn btn-success' %>
<% end %>
<br/><br/>


<%= link_to 'Back to post', topic_posts_path, class: 'btn btn-secondary' %> <br/>

<script>
    $(document).ready(function(){
        $.ajax({
            url: "/topics/"+"<%= @topic.id %>"+"/posts/"+"<%= @post.id %>"+"/updatestatus",
            type: 'POST'
        });
    });
</script>